### ISSUE TITLE
Disable vibration

### ISSUE THREAD

**Issue by razcampagne** [monich/openrepos-clock-settings#8]
Hi,
Would there be a way to disable vibrations for alarms regardless of the global settings ?
Sorry for using your app for such a question but I wanted to look at how you managed to change the volume setting but I can't figure out D-Bus for this particular case…

**Comment by monich** [comment]
Sorry, I don't know off the top of my head. My guess is that vibra is part of profile (or part of feedback definition included in the profile, or something of that sort), I would start digging in that direction if I wanted to figure it out...

**Comment by monich** [comment]
Just came across a relevant piece of information, while working on something else. Check out `/usr/share/ngfd/events.d/` directory on the device and `.ini` files there. The default vibra behavior is hardcoded there, it may or may not be possible to alter it over D-Bus. [ngfd](https://git.merproject.org/mer-core/ngfd) (Non-Graphical Feedback Daemon) is the component responsible for that.

**Comment by razcampagne** [comment]
Wow, nice! Thanks a lot for the follow-up!
